SilverStripe\CMS\Model\SiteTree:
  extensions:
    - jzubero\SiteTreeLabels\Extensions\SiteTreeExtension
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'jzubero/silverstripe-sitetree-labels: client/css/sitetree-labels.css'